### ISSUE TITLE
ConstantMethodRef cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by YiZero10** [i-net-software/JWebAssembly#64]
I have been blocked...
I want to compile Java smart contract, is there any sample?
And the Picture is my code, I want to complie it to wasm. And happen following exceptions:

Exception in thread "main" de.inetsoftware.jwebassembly.WasmException: java.lang.ClassCastException: class de.inetsoftware.classparser.ConstantMethodRef cannot be cast to class java.lang.String (de.inetsoftware.classparser.ConstantMethodRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at MyBank.createAccount(MyBank.java:19)
	at de.inetsoftware.jwebassembly.WasmException.create(WasmException.java:145)
	at de.inetsoftware.jwebassembly.WasmException.create(WasmException.java:118)
	at de.inetsoftware.jwebassembly.WasmException.create(WasmException.java:99)
	at de.inetsoftware.jwebassembly.module.JavaMethodWasmCodeBuilder.writeCode(JavaMethodWasmCodeBuilder.java:767)
	at de.inetsoftware.jwebassembly.module.JavaMethodWasmCodeBuilder.buildCode(JavaMethodWasmCodeBuilder.java:99)
	at de.inetsoftware.jwebassembly.module.ModuleGenerator.createInstructions(ModuleGenerator.java:586)
	at de.inetsoftware.jwebassembly.module.ModuleGenerator.scanFunctions(ModuleGenerator.java:242)
	at de.inetsoftware.jwebassembly.module.ModuleGenerator.prepareFinish(ModuleGenerator.java:325)
	at de.inetsoftware.jwebassembly.JWebAssembly.compile(JWebAssembly.java:368)
	at de.inetsoftware.jwebassembly.JWebAssembly.compileToText(JWebAssembly.java:279)
	at de.inetsoftware.jwebassembly.JWebAssembly.compileToText(JWebAssembly.java:263)
	at de.inetsoftware.jwebassembly.JWebAssembly.compileToText(JWebAssembly.java:229)
	at Test.main(Test.java:31)
Caused by: java.lang.ClassCastException: class de.inetsoftware.classparser.ConstantMethodRef cannot be cast to class java.lang.String (de.inetsoftware.classparser.ConstantMethodRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at de.inetsoftware.classparser.BootstrapMethod.<init>(BootstrapMethod.java:58)
	at de.inetsoftware.classparser.ClassFile.getBootstrapMethod(ClassFile.java:234)
	at de.inetsoftware.jwebassembly.module.JavaMethodWasmCodeBuilder.writeCode(JavaMethodWasmCodeBuilder.java:662)
	... 9 more

<img width="878" alt="image" src="https://github.com/i-net-software/JWebAssembly/assets/45324620/2f4817d2-4479-45cf-9551-bb831433e92c">

**Comment by Horcrux7** [comment]
* Do you have use Java 8? Currently for the most cases it work only with the Java 8 runtime.

* Which version of JWebAssembly do you have use? Try the current snapshot version. It include many bug fixes.

* How can I reproduce it? Please attache an sample.

**Comment by wlusergithub** [comment]
> I have been blocked... I want to compile Java smart contract, is there any sample? And the Picture is my code, I want to complie it to wasm. And happen following exceptions:
> 
> Exception in thread "main" de.inetsoftware.jwebassembly.WasmException: java.lang.ClassCastException: class de.inetsoftware.classparser.ConstantMethodRef cannot be cast to class java.lang.String (de.inetsoftware.classparser.ConstantMethodRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') at MyBank.createAccount(MyBank.java:19) at de.inetsoftware.jwebassembly.WasmException.create(WasmException.java:145) at de.inetsoftware.jwebassembly.WasmException.create(WasmException.java:118) at de.inetsoftware.jwebassembly.WasmException.create(WasmException.java:99) at de.inetsoftware.jwebassembly.module.JavaMethodWasmCodeBuilder.writeCode(JavaMethodWasmCodeBuilder.java:767) at de.inetsoftware.jwebassembly.module.JavaMethodWasmCodeBuilder.buildCode(JavaMethodWasmCodeBuilder.java:99) at de.inetsoftware.jwebassembly.module.ModuleGenerator.createInstructions(ModuleGenerator.java:586) at de.inetsoftware.jwebassembly.module.ModuleGenerator.scanFunctions(ModuleGenerator.java:242) at de.inetsoftware.jwebassembly.module.ModuleGenerator.prepareFinish(ModuleGenerator.java:325) at de.inetsoftware.jwebassembly.JWebAssembly.compile(JWebAssembly.java:368) at de.inetsoftware.jwebassembly.JWebAssembly.compileToText(JWebAssembly.java:279) at de.inetsoftware.jwebassembly.JWebAssembly.compileToText(JWebAssembly.java:263) at de.inetsoftware.jwebassembly.JWebAssembly.compileToText(JWebAssembly.java:229) at Test.main(Test.java:31) Caused by: java.lang.ClassCastException: class de.inetsoftware.classparser.ConstantMethodRef cannot be cast to class java.lang.String (de.inetsoftware.classparser.ConstantMethodRef is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') at de.inetsoftware.classparser.BootstrapMethod.(BootstrapMethod.java:58) at de.inetsoftware.classparser.ClassFile.getBootstrapMethod(ClassFile.java:234) at de.inetsoftware.jwebassembly.module.JavaMethodWasmCodeBuilder.writeCode(JavaMethodWasmCodeBuilder.java:662) ... 9 more
> 
> <img alt="image" width="878" src="https://private-user-images.githubusercontent.com/45324620/266942899-2f4817d2-4479-45cf-9551-bb831433e92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTczOTAsIm5iZiI6MTcwMTc1NzA5MCwicGF0aCI6Ii80NTMyNDYyMC8yNjY5NDI4OTktMmY0ODE3ZDItNDQ3OS00NWNmLTk1NTEtYmI4MzE0MzNlOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNmI5MjMxNGU5ODEwNjIyYTdhZDMwOWI2YTc4YzU3MGYxYTc3ZThlMzY3MjgyNGQ5NGU1OTYxZTVlZmQyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OlsDv-CNFQfpI3g6BvCfI9B0hagsq-FZXt_qqyPNuoM">

请问下您这是在将java编译成wasm智能合约吗

**Comment by Horcrux7** [comment]
I repeat the questions:

* Do you have use Java 8? Currently for the most cases it work only with the Java 8 runtime.

* Which version of JWebAssembly do you have use? Try the current snapshot version. It include many bug fixes.

* How can I reproduce it? Please attache an sample.
